-- Run this in your Supabase SQL Editor

-- 1. Enable UUID extension (usually enabled by default, but good to ensure)
create extension if not exists "uuid-ossp";

-- 2. Sessions Table (Track anonymous users)
create table if not exists public.sessions (
  id uuid primary key default uuid_generate_v4(),
  guest_uuid uuid not null, -- The ID generating on client-side (localStorage)
  ip_hash text, -- Optional: Store hashed IP for simple ban/limiting
  user_agent text, -- Optional: Device info
  last_seen timestamptz default now(),
  created_at timestamptz default now(),
  
  -- Ensure one session row per guest_uuid
  constraint sessions_guest_uuid_key unique (guest_uuid)
);

-- 3. Strokes Table (History of pixels)
create table if not exists public.strokes (
  id bigint generated by default as identity primary key,
  session_id uuid references public.sessions(id), -- Link to session
  x int2 not null, -- Small int (up to 32767) fits 3000 width
  y int2 not null,
  color char(7) not null, -- Hex color #RRGGBB
  team text, -- 'red', 'blue', etc.
  created_at timestamptz default now()
);

-- 4. Indexes for performance
create index if not exists idx_strokes_created_at on public.strokes(created_at desc);
create index if not exists idx_strokes_session_id on public.strokes(session_id);

-- 5. RLS Policies (Optional but Recommended)
alter table public.sessions enable row level security;
alter table public.strokes enable row level security;

-- Allow server (service_role) to do everything. 
-- If you want public read access (for analytics), add:
create policy "Enable read access for all users" on public.strokes for select using (true);
